### PR TITLE
Add support for webhook updates

### PR DESCRIPTION
**Pull request by mvn23**
As the title says, we can use webhooks to push our updates.
This will avoid the need for an all-access long-lived token.

### CODE REVIEW

**Comment by Johboh** [comment]
Thanks! Will take a proper look in a couple of days. Currently out traveling without computer.

**Comment by Johboh** [comment]
Looks good! Will deploy this weekend (if covid-19 does not cancel another flight for me).

**Comment by Johboh** [comment]
@mvn23 Deployed on Play Store

**Comment by mvn23** [comment]
Awesome, thanks!

**Pull request merged**
